// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using R59_M11_Class_01_Work_02.Models_;

#nullable disable

namespace R59_M11_Class_01_Work_02.Migrations
{
    [DbContext(typeof(DeviceDbContext))]
    [Migration("20240924095924_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("R59_M11_Class_01_Work_02.Models_.CommonSpec", b =>
                {
                    b.Property<int>("CommonSpecId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommonSpecId"));

                    b.Property<string>("SpecName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("CommonSpecId");

                    b.ToTable("CommonSpecs");

                    b.HasData(
                        new
                        {
                            CommonSpecId = 1,
                            SpecName = "RAM"
                        },
                        new
                        {
                            CommonSpecId = 2,
                            SpecName = "Display"
                        },
                        new
                        {
                            CommonSpecId = 3,
                            SpecName = "Storage"
                        });
                });

            modelBuilder.Entity("R59_M11_Class_01_Work_02.Models_.Device", b =>
                {
                    b.Property<int>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeviceId"));

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("DeviceType")
                        .HasColumnType("int");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal?>("Price")
                        .IsRequired()
                        .HasColumnType("money");

                    b.Property<DateTime?>("RealeseDate")
                        .IsRequired()
                        .HasColumnType("date");

                    b.HasKey("DeviceId");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            DeviceId = 1,
                            DeviceName = "Samsung M55",
                            DeviceType = 1,
                            InStock = true,
                            Picture = "1.jpg",
                            Price = 42000.00m,
                            RealeseDate = new DateTime(2023, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("R59_M11_Class_01_Work_02.Models_.Spec", b =>
                {
                    b.Property<int>("SpecId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpecId"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("SpecName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("SpecId");

                    b.HasIndex("DeviceId");

                    b.ToTable("Specs");

                    b.HasData(
                        new
                        {
                            SpecId = 1,
                            DeviceId = 1,
                            SpecName = "RAM",
                            Value = "6GB"
                        },
                        new
                        {
                            SpecId = 2,
                            DeviceId = 1,
                            SpecName = "Display",
                            Value = "5.8in"
                        });
                });

            modelBuilder.Entity("R59_M11_Class_01_Work_02.Models_.Spec", b =>
                {
                    b.HasOne("R59_M11_Class_01_Work_02.Models_.Device", "Device")
                        .WithMany("Specs")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("R59_M11_Class_01_Work_02.Models_.Device", b =>
                {
                    b.Navigation("Specs");
                });
#pragma warning restore 612, 618
        }
    }
}
